[build]
  command = "yarn build"
  publish = "www/public"
  functions = "functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Content-Security-Policy = "prefetch-src 'self'; default-src 'self'; manifest-src 'self'; style-src 'self' 'unsafe-inline'; base-uri 'none'; connect-src 'self' https://us-central1-contact-form-test-ab6ae.cloudfunctions.net; frame-src *.google.com www.youtube.com; frame-ancestors 'none'; form-action 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval' maps.googleapis.com www.google-analytics.com;img-src data: 'self' maps.gstatic.com *.googleapis.com *.ggpht www.google-analytics.com *.ytimg.com;"

[[headers]]
  for = "/*.*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "404.html"
  [headers.values]
    Cache-Control = "max-age=300"

[[redirects]]
  from = "/en/*"
  to = "/en/404"
  status = 404

[[redirects]]
  from = "/ru/*"
  to = "/ru/404"
  status = 404
